### ISSUE TITLE
Phase 1: Basics of menus 

### ISSUE THREAD

**Issue by satayyeb** [AdvancedProgrammingSUT2022/project-group-19#19]
## Description
تکمیل منو ها. شامل اضافه کردن عضو جدید و ویرایش اطلاعات

**Comment by shalchianmh** [comment]
کاش اینو چند تیکه میکردیم
آخه منوها خیلی زیادن

**Comment by satayyeb** [comment]
> کاش اینو چند تیکه میکردیم آخه منوها خیلی زیادن

راست میگی الان ردیفش می کنم
